services:

  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    env_file:
      - .env
    volumes:
      - database-16-3:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  php-8.3:
    image: ghcr.io/digital-craftsman-de/deserializing-connection-php-8.3
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  php-8.4:
    image: ghcr.io/digital-craftsman-de/deserializing-connection-php-8.4
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  database-16-3: ~
